name: "dependabot approve-and-request-merge"

on:
  pull_request_target

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: contentful/dependabot-auto-merge@v1
        with:
          github_token: ${{ secrets.VAULT_URL }}
